version: 0.2

phases:
  install:
    commands:
      # 依存ライブラリを一時フォルダ package/ にインストール
      - pip install -r requirements.txt -t package
  pre_build:
    commands:
      - |
        CURRENT_VERSION=$(
          aws lambda get-alias \
            --function-name demo-manual-deploy \
            --name prod \
            --query FunctionVersion \
            --output text
        )
  build:
    commands:
      # コードを ZIP 化
      - mkdir -p package
      - pip install -r requirements.txt -t package
      - cp src/lambda_function.py package/
      - cd package && zip -r ../function.zip . && cd ..
      # 新バージョンを発行
      - TARGET_VERSION=$(aws lambda publish-version \
          --function-name demo-manual-deploy \
          --query Version \
          --output text)
      # AppSpec に CurrentVersion/TargetVersion を埋め込む
      - sed -i \
          -e "s/{{CurrentVersion}}/$CURRENT_VERSION/" \
          -e "s/{{TargetVersion}}/$TARGET_VERSION/" \
          appspec.yml

artifacts:
  files:
    - appspec.yml    # CodeDeploy 旧フロー用。後で不要なら消してOK
    - function.zip   # デプロイ対象のZIPアーティファクト
