version: 0.2

phases:
  install:
    commands:
      # 依存ライブラリを一時フォルダ package/ にインストール
      - pip install -r requirements.txt -t package
  build:
    commands:
      # ハンドラをコピーして ZIP 化
      - cp src/lambda_function.py package/
      - cd package && zip -r ../function.zip . && cd ..
  # post_build:
  #   commands:
  #     # S3 バケットへアップロード（<YourArtifactBucket> は実際のバケット名に置き換え）
  #     - aws s3 cp function.zip s3://lambda-func-deploy-demo/function-v1.zip

artifacts:
  files:
    - appspec.yml    # CodeDeploy 旧フロー用。後で不要なら消してOK
    - function.zip   # デプロイ対象のZIPアーティファクト
