version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # 依存ライブラリを一時フォルダ package/ にインストール
      - pip install -r requirements.txt -t package
  
  build:
    commands:
      # パッケージディレクトリを作成
      - mkdir -p package
      # 依存ライブラリをインストール
      - pip install -r requirements.txt -t package
      # ハンドラをコピー
      - cp src/lambda_function.py package/
      # ZIP化（S3アップロード用）
      - cd package && zip -r ../function.zip . && cd ..
      
      # CodePipelineのLambdaアクション用にルートレベルにファイルをコピー
      - cp src/lambda_function.py ./
  
  post_build:
    commands:
      # S3 バケットへアップロード（バックアップ・手動デプロイ用）
      - aws s3 cp function.zip s3://lambda-func-deploy-demo/function-v1.zip
      - echo "Build completed successfully"

artifacts:
  files:
    # CodePipelineのLambdaアクション用（ルートレベルのファイル）
    - lambda_function.py
    - requirements.txt
    # function.zipは除外（Lambda関数に不要、S3バックアップのみ）
